#设置自己的程序名称
spring:
  application:
    name: xal-client1
  #thymeleaf 配置
  thymeleaf:
    encoding: UTF-8
    prefix: classpath:/templates
    cache: false
#服务注册中心地址（刚刚搭建的Eureka Server的地址）
eureka:
  client:
    #是否向服务中心注册自己
    register-with-eureka: false
    #设置eureka服务中心的地址
    service-url:
      defaultZone: http://localhost:8888/eureka
#设置自己启动的端口
server:
  port: 9991